# -*- coding: utf-8 -*-
"""ThesisImpV3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PFjTN8_Eh_6LPhYGU65Zo--UGvMwD27m
"""

!pip install torch torchvision torchaudio
!pip install torch-geometric
!pip install pandas numpy matplotlib seaborn scikit-learn
!pip install networkx tqdm

import pandas as pd
import numpy as np
import networkx as nx

import torch
import torch.nn.functional as F

from torch_geometric.data import Data
from torch_geometric.nn import GCNConv,GATConv,SAGEConv

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    average_precision_score,
    roc_curve,
    precision_recall_curve
)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import IsolationForest

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

import matplotlib.pyplot as plt
import seaborn as sns

from tqdm import tqdm

from google.colab import drive
drive.mount('/content/drive')

BASE_PATH = "/content/drive/MyDrive/Elliptic"

FEATURE_FILE = f"{BASE_PATH}/elliptic_txs_features.csv"
CLASS_FILE   = f"{BASE_PATH}/elliptic_txs_classes.csv"
EDGE_FILE    = f"{BASE_PATH}/elliptic_txs_edgelist.csv"

features = pd.read_csv(FEATURE_FILE, header=None)

classes = pd.read_csv(CLASS_FILE)

edges = pd.read_csv(EDGE_FILE)

print(features.shape)
print(classes.shape)
print(edges.shape)

feature_cols = ["txId"] + [f"f{i}" for i in range(166)]

features.columns = feature_cols

features.head()

data = features.merge(classes,on="txId")

data.head()

data['class'] = data['class'].replace({
    '1':1,
    '2':0,
    'unknown':-1
})

data = data[data['class']!=-1]

print(data['class'].value_counts())

plt.figure(figsize=(7,5))

sns.countplot(x=data['class'])

plt.title("Class Distribution")
plt.show()

corr = data.iloc[:,1:31].corr()

plt.figure(figsize=(12,10))

sns.heatmap(corr,cmap='coolwarm')

plt.title("Feature Correlation Heatmap")

plt.show()

corr_target = data.corr(numeric_only=True)['class'].abs()

top10 = corr_target.sort_values(
    ascending=False
).head(11)

top10

top10[1:].plot(kind='bar')

plt.title("Top Features Correlated with Class")

plt.show()

node_ids = data['txId'].values

X = data.drop(columns=['txId','class']).values

y = data['class'].values

scaler = StandardScaler()

X = scaler.fit_transform(X)

node_map = {
    node:i
    for i,node in enumerate(node_ids)
}

edge_index=[]

for _,row in tqdm(edges.iterrows(),total=len(edges)):

    s=row['txId1']
    d=row['txId2']

    if s in node_map and d in node_map:

        edge_index.append([
            node_map[s],
            node_map[d]
        ])

edge_index=np.array(edge_index)

x=torch.tensor(X,dtype=torch.float)

y=torch.tensor(y,dtype=torch.long)

edge_index=torch.tensor(
    edge_index.T,
    dtype=torch.long
)

graph_data = Data(
    x=x,
    edge_index=edge_index,
    y=y
)

graph_data

idx=np.arange(len(y))

train_idx,test_idx=train_test_split(
    idx,
    test_size=0.2,
    stratify=y,
    random_state=42
)

train_mask=torch.zeros(len(y),dtype=torch.bool)
test_mask=torch.zeros(len(y),dtype=torch.bool)

train_mask[train_idx]=True
test_mask[test_idx]=True

graph_data.train_mask=train_mask
graph_data.test_mask=test_mask

import numpy as np
import pandas as pd

results=[]

def evaluate_model(
        model,
        data,
        model_name):

    model.eval()

    with torch.no_grad():

        logits=model(data.x,data.edge_index)

        probs=F.softmax(logits,dim=1)

        pred=probs.argmax(dim=1)

    y_true=data.y[data.test_mask].cpu().numpy()

    y_pred=pred[data.test_mask].cpu().numpy()

    y_prob=probs[data.test_mask][:,1].cpu().numpy()

    acc=accuracy_score(y_true,y_pred)

    prec=precision_score(
        y_true,
        y_pred,
        zero_division=0
    )

    rec=recall_score(
        y_true,
        y_pred,
        zero_division=0
    )

    f1=f1_score(
        y_true,
        y_pred,
        zero_division=0
    )

    roc=roc_auc_score(
        y_true,
        y_prob
    )

    pr=average_precision_score(
        y_true,
        y_prob
    )

    results.append([
        model_name,
        acc,
        prec,
        rec,
        f1,
        roc,
        pr
    ])

    print("\n",model_name)

    print(classification_report(
        y_true,
        y_pred
    ))

    return y_true,y_pred,y_prob

class GCN(torch.nn.Module):

    def __init__(self,
                 in_channels,
                 hidden=128):

        super().__init__()

        self.conv1=GCNConv(
            in_channels,
            hidden
        )

        self.conv2=GCNConv(
            hidden,
            2
        )

    def forward(
        self,
        x,
        edge_index
    ):

        x=self.conv1(
            x,
            edge_index
        )

        x=F.relu(x)

        x=F.dropout(
            x,
            p=0.3,
            training=self.training
        )

        x=self.conv2(
            x,
            edge_index
        )

        return x

def train_gnn(
        model,
        data,
        epochs=100,
        lr=0.001):

    optimizer=torch.optim.Adam(
        model.parameters(),
        lr=lr,
        weight_decay=5e-4
    )

    criterion=torch.nn.CrossEntropyLoss()

    losses=[]

    for epoch in range(epochs):

        model.train()

        optimizer.zero_grad()

        out=model(
            data.x,
            data.edge_index
        )

        loss=criterion(
            out[data.train_mask],
            data.y[data.train_mask]
        )

        loss.backward()

        optimizer.step()

        losses.append(loss.item())

        if epoch%10==0:

            print(
                f"Epoch {epoch} Loss {loss.item():.4f}"
            )

    return losses

gcn=GCN(
    graph_data.num_features
)

gcn_losses=train_gnn(
    gcn,
    graph_data,
    epochs=100
)

plt.figure(figsize=(8,5))

plt.plot(gcn_losses)

plt.title(
    "GCN Training Loss"
)

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.show()

gcn_true,\
gcn_pred,\
gcn_prob = evaluate_model(
    gcn,
    graph_data,
    "GCN"
)

cm=confusion_matrix(
    gcn_true,
    gcn_pred
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.title(
    "GCN Confusion Matrix"
)

plt.show()

class GAT(torch.nn.Module):

    def __init__(
            self,
            in_channels):

        super().__init__()

        self.gat1=GATConv(
            in_channels,
            64,
            heads=4
        )

        self.gat2=GATConv(
            64*4,
            2,
            heads=1
        )

    def forward(
            self,
            x,
            edge_index):

        x=self.gat1(
            x,
            edge_index
        )

        x=F.elu(x)

        x=F.dropout(
            x,
            p=0.3,
            training=self.training
        )

        x=self.gat2(
            x,
            edge_index
        )

        return x

gat=GAT(
    graph_data.num_features
)

gat_losses=train_gnn(
    gat,
    graph_data,
    epochs=100
)

plt.figure(figsize=(8,5))

plt.plot(gat_losses)

plt.title(
    "GAT Training Loss"
)

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.show()

gat_true,\
gat_pred,\
gat_prob=evaluate_model(
    gat,
    graph_data,
    "GAT"
)

cm=confusion_matrix(
    gat_true,
    gat_pred
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.title(
    "GAT Confusion Matrix"
)

plt.show()

class GraphSAGE(torch.nn.Module):

    def __init__(
            self,
            in_channels):

        super().__init__()

        self.sage1=SAGEConv(
            in_channels,
            128
        )

        self.sage2=SAGEConv(
            128,
            2
        )

    def forward(
            self,
            x,
            edge_index):

        x=self.sage1(
            x,
            edge_index
        )

        x=F.relu(x)

        x=F.dropout(
            x,
            p=0.3,
            training=self.training
        )

        x=self.sage2(
            x,
            edge_index
        )

        return x

sage=GraphSAGE(
    graph_data.num_features
)

sage_losses=train_gnn(
    sage,
    graph_data,
    epochs=100
)

plt.figure(figsize=(8,5))

plt.plot(sage_losses)

plt.title(
    "GraphSAGE Training Loss"
)

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.show()

sage_true,\
sage_pred,\
sage_prob=evaluate_model(
    sage,
    graph_data,
    "GraphSAGE"
)

cm=confusion_matrix(
    sage_true,
    sage_pred
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.title(
    "GraphSAGE Confusion Matrix"
)

plt.show()

gnn_outputs={

    "GCN":{
        "true":gcn_true,
        "pred":gcn_pred,
        "prob":gcn_prob
    },

    "GAT":{
        "true":gat_true,
        "pred":gat_pred,
        "prob":gat_prob
    },

    "GraphSAGE":{
        "true":sage_true,
        "pred":sage_pred,
        "prob":sage_prob
    }
}

gnn_results=pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1",
        "ROC_AUC",
        "PR_AUC"
    ]
)

gnn_results

gnn_results.to_csv(
    f"{BASE_PATH}/gnn_results.csv",
    index=False
)

print("Saved")

X_train = X[train_idx]
X_test  = X[test_idx]

y_train = y[train_idx].cpu().numpy()
y_test  = y[test_idx].cpu().numpy()

print(X_train.shape)
print(X_test.shape)

lr = LogisticRegression(
    max_iter=500,
    n_jobs=-1
)

lr.fit(
    X_train,
    y_train
)

lr_pred = lr.predict(X_test)

lr_prob = lr.predict_proba(X_test)[:,1]

acc = accuracy_score(y_test,lr_pred)

prec = precision_score(y_test,lr_pred)

rec = recall_score(y_test,lr_pred)

f1 = f1_score(y_test,lr_pred)

roc = roc_auc_score(y_test,lr_prob)

pr = average_precision_score(
    y_test,
    lr_prob
)

results.append([
    "Logistic Regression",
    acc,
    prec,
    rec,
    f1,
    roc,
    pr
])

print(classification_report(
    y_test,
    lr_pred
))

cm = confusion_matrix(
    y_test,
    lr_pred
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.title(
    "Logistic Regression"
)

plt.show()

iso = IsolationForest(
    contamination=0.02,
    random_state=42,
    n_estimators=200
)

iso.fit(X_train)

iso_pred = iso.predict(X_test)

iso_pred = np.where(
    iso_pred==-1,
    1,
    0
)

iso_score = -iso.score_samples(
    X_test
)

acc = accuracy_score(
    y_test,
    iso_pred
)

prec = precision_score(
    y_test,
    iso_pred,
    zero_division=0
)

rec = recall_score(
    y_test,
    iso_pred,
    zero_division=0
)

f1 = f1_score(
    y_test,
    iso_pred,
    zero_division=0
)

roc = roc_auc_score(
    y_test,
    iso_score
)

pr = average_precision_score(
    y_test,
    iso_score
)

results.append([
    "Isolation Forest",
    acc,
    prec,
    rec,
    f1,
    roc,
    pr
])

print(classification_report(
    y_test,
    iso_pred
))

cm = confusion_matrix(
    y_test,
    iso_pred
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.title(
    "Isolation Forest"
)

plt.show()

input_dim = X_train.shape[1]

autoencoder = Sequential([

    Dense(
        128,
        activation='relu',
        input_shape=(input_dim,)
    ),

    Dense(
        64,
        activation='relu'
    ),

    Dense(
        32,
        activation='relu'
    ),

    Dense(
        64,
        activation='relu'
    ),

    Dense(
        128,
        activation='relu'
    ),

    Dense(
        input_dim,
        activation='linear'
    )
])

autoencoder.compile(
    optimizer='adam',
    loss='mse'
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = autoencoder.fit(
    X_train,
    X_train,
    epochs=50,
    batch_size=512,
    validation_split=0.1,
    callbacks=[early_stop],
    verbose=1
)

plt.figure(figsize=(8,5))

plt.plot(
    history.history['loss'],
    label='train'
)

plt.plot(
    history.history['val_loss'],
    label='validation'
)

plt.legend()

plt.title(
    "Autoencoder Training"
)

plt.show()

recon = autoencoder.predict(
    X_test
)

mse = np.mean(
    np.square(
        X_test-recon
    ),
    axis=1
)

threshold = np.percentile(
    mse,
    95
)

ae_pred = (
    mse > threshold
).astype(int)

acc = accuracy_score(
    y_test,
    ae_pred
)

prec = precision_score(
    y_test,
    ae_pred,
    zero_division=0
)

rec = recall_score(
    y_test,
    ae_pred,
    zero_division=0
)

f1 = f1_score(
    y_test,
    ae_pred,
    zero_division=0
)

roc = roc_auc_score(
    y_test,
    mse
)

pr = average_precision_score(
    y_test,
    mse
)

results.append([
    "Autoencoder",
    acc,
    prec,
    rec,
    f1,
    roc,
    pr
])

print(classification_report(
    y_test,
    ae_pred
))

cm = confusion_matrix(
    y_test,
    ae_pred
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.title(
    "Autoencoder"
)

plt.show()

final_results = pd.DataFrame(

    results,

    columns=[

        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1",
        "ROC_AUC",
        "PR_AUC"
    ]
)

final_results.sort_values(
    by="F1",
    ascending=False,
    inplace=True
)

final_results

final_results.to_csv(

    f"{BASE_PATH}/Final_Model_Results.csv",

    index=False
)

plt.figure(figsize=(10,5))

sns.barplot(

    x="Model",

    y="Accuracy",

    data=final_results
)

plt.xticks(rotation=45)

plt.title(
    "Accuracy Comparison"
)

plt.show()

plt.figure(figsize=(10,5))

sns.barplot(

    x="Model",

    y="Precision",

    data=final_results
)

plt.xticks(rotation=45)

plt.show()

plt.figure(figsize=(10,5))

sns.barplot(

    x="Model",

    y="Recall",

    data=final_results
)

plt.xticks(rotation=45)

plt.show()

plt.figure(figsize=(10,5))

sns.barplot(

    x="Model",

    y="F1",

    data=final_results
)

plt.xticks(rotation=45)

plt.show()

plt.figure(figsize=(10,8))

for name,obj in gnn_outputs.items():

    fpr,tpr,_ = roc_curve(
        obj["true"],
        obj["prob"]
    )

    plt.plot(
        fpr,
        tpr,
        label=name
    )

fpr,tpr,_ = roc_curve(
    y_test,
    lr_prob
)

plt.plot(
    fpr,
    tpr,
    label="Logistic Regression"
)

fpr,tpr,_ = roc_curve(
    y_test,
    iso_score
)

plt.plot(
    fpr,
    tpr,
    label="Isolation Forest"
)

fpr,tpr,_ = roc_curve(
    y_test,
    mse
)

plt.plot(
    fpr,
    tpr,
    label="Autoencoder"
)

plt.plot(
    [0,1],
    [0,1],
    '--'
)

plt.legend()

plt.title("ROC Curve")

plt.show()

plt.figure(figsize=(10,8))

for name,obj in gnn_outputs.items():

    p,r,_ = precision_recall_curve(
        obj["true"],
        obj["prob"]
    )

    plt.plot(
        r,
        p,
        label=name
    )

p,r,_ = precision_recall_curve(
    y_test,
    lr_prob
)

plt.plot(
    r,
    p,
    label="Logistic Regression"
)

p,r,_ = precision_recall_curve(
    y_test,
    iso_score
)

plt.plot(
    r,
    p,
    label="Isolation Forest"
)

p,r,_ = precision_recall_curve(
    y_test,
    mse
)

plt.plot(
    r,
    p,
    label="Autoencoder"
)

plt.legend()

plt.title(
    "Precision Recall Curve"
)

plt.show()

ranking = final_results.sort_values(
    by="F1",
    ascending=False
)

ranking

best_model = ranking.iloc[0]

print(
    best_model
)

with pd.ExcelWriter(

    f"{BASE_PATH}/Dissertation_Results.xlsx"

) as writer:

    final_results.to_excel(
        writer,
        sheet_name="Model Results",
        index=False
    )

print("Export Complete")

chapter4_table = final_results.copy()

chapter4_table.round(4)

!pip install xgboost
!pip install lightgbm
!pip install catboost
!pip install node2vec

from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from lightgbm import LGBMClassifier

from catboost import CatBoostClassifier

from sklearn.neural_network import MLPClassifier

rf = RandomForestClassifier(

    n_estimators=500,
    max_depth=20,
    random_state=42,
    n_jobs=-1
)

rf.fit(
    X_train,
    y_train
)

rf_pred = rf.predict(X_test)

rf_prob = rf.predict_proba(X_test)[:,1]

acc = accuracy_score(y_test,rf_pred)

prec = precision_score(y_test,rf_pred)

rec = recall_score(y_test,rf_pred)

f1 = f1_score(y_test,rf_pred)

roc = roc_auc_score(
    y_test,
    rf_prob
)

pr = average_precision_score(
    y_test,
    rf_prob
)

results.append([
    "Random Forest",
    acc,
    prec,
    rec,
    f1,
    roc,
    pr
])

xgb = XGBClassifier(

    n_estimators=500,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='logloss',
    random_state=42
)

xgb.fit(
    X_train,
    y_train
)

xgb_pred = xgb.predict(X_test)

xgb_prob = xgb.predict_proba(X_test)[:,1]

results.append([

    "XGBoost",

    accuracy_score(y_test,xgb_pred),

    precision_score(y_test,xgb_pred),

    recall_score(y_test,xgb_pred),

    f1_score(y_test,xgb_pred),

    roc_auc_score(y_test,xgb_prob),

    average_precision_score(
        y_test,
        xgb_prob
    )
])

lgbm = LGBMClassifier(

    n_estimators=500,
    learning_rate=0.05,
    random_state=42
)

lgbm.fit(
    X_train,
    y_train
)

lgb_pred = lgbm.predict(X_test)

lgb_prob = lgbm.predict_proba(X_test)[:,1]

results.append([

    "LightGBM",

    accuracy_score(y_test,lgb_pred),

    precision_score(y_test,lgb_pred),

    recall_score(y_test,lgb_pred),

    f1_score(y_test,lgb_pred),

    roc_auc_score(y_test,lgb_prob),

    average_precision_score(
        y_test,
        lgb_prob
    )
])

y_train_np = y_train

y_test_np = y_test

cat = CatBoostClassifier(

    iterations=500,
    learning_rate=0.05,
    depth=8,
    loss_function='Logloss',
    eval_metric='F1',
    verbose=100,
    random_seed=42
)

cat.fit(
    X_train,
    y_train_np
)

cat_pred = cat.predict(X_test)

cat_prob = cat.predict_proba(X_test)[:,1]

results.append([

    "CatBoost",

    accuracy_score(y_test,cat_pred),

    precision_score(y_test,cat_pred),

    recall_score(y_test,cat_pred),

    f1_score(y_test,cat_pred),

    roc_auc_score(y_test,cat_prob),

    average_precision_score(
        y_test,
        cat_prob
    )
])

mlp = MLPClassifier(

    hidden_layer_sizes=(256,128,64),

    max_iter=100,

    random_state=42
)

mlp.fit(
    X_train,
    y_train
)

mlp_pred = mlp.predict(X_test)

mlp_prob = mlp.predict_proba(X_test)[:,1]

results.append([

    "MLP",

    accuracy_score(y_test,mlp_pred),

    precision_score(y_test,mlp_pred),

    recall_score(y_test,mlp_pred),

    f1_score(y_test,mlp_pred),

    roc_auc_score(y_test,mlp_prob),

    average_precision_score(
        y_test,
        mlp_prob
    )
])

import networkx as nx

G = nx.Graph()

G.add_edges_from(
    edge_index.T.numpy()
)

from node2vec import Node2Vec

node2vec = Node2Vec(

    G,

    dimensions=64,

    walk_length=10,

    num_walks=20,

    workers=4
)

model = node2vec.fit(
    window=10,
    min_count=1
)

eembeddings = []

dim = model.vector_size

for i in range(len(node_ids)):

    key = str(i)

    if key in model.wv:

        embeddings.append(
            model.wv[key]
        )

    else:

        embeddings.append(
            np.zeros(dim)
        )

embeddings = np.array(embeddings)

print(embeddings.shape)

X_train_emb = embeddings[train_idx]

X_test_emb = embeddings[test_idx]

rf_embed = RandomForestClassifier(

    n_estimators=500,

    random_state=42
)

rf_embed.fit(
    X_train_emb,
    y_train
)

pred = rf_embed.predict(
    X_test_emb
)

prob = rf_embed.predict_proba(
    X_test_emb
)[:,1]

results.append([

    "Node2Vec+RF",

    accuracy_score(y_test,pred),

    precision_score(y_test,pred),

    recall_score(y_test,pred),

    f1_score(y_test,pred),

    roc_auc_score(y_test,prob),

    average_precision_score(
        y_test,
        prob
    )
])

xgb_embed = XGBClassifier(

    n_estimators=500,

    max_depth=8,

    eval_metric='logloss'
)

xgb_embed.fit(
    X_train_emb,
    y_train
)

pred = xgb_embed.predict(
    X_test_emb
)

prob = xgb_embed.predict_proba(
    X_test_emb
)[:,1]

results.append([

    "Node2Vec+XGBoost",

    accuracy_score(y_test,pred),

    precision_score(y_test,pred),

    recall_score(y_test,pred),

    f1_score(y_test,pred),

    roc_auc_score(y_test,prob),

    average_precision_score(
        y_test,
        prob
    )
])

comparison = pd.DataFrame(

    results,

    columns=[

        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1",
        "ROC_AUC",
        "PR_AUC"
    ]
)

comparison.sort_values(

    by="F1",

    ascending=False,

    inplace=True
)

comparison

comparison.to_csv(

    f"{BASE_PATH}/Complete_Model_Comparison.csv",

    index=False
)